services:
  mongo:
    image: mongo:${MONGO_TAG:-latest}
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT_HOST}:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PWD}
    volumes:
      - mongo_data:/data/db
      - ./init:/docker-entrypoint-initdb.d:ro

  mongo-express:
    image: mongo-express:${ME_TAG:-latest}
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "${ME_PORT_HOST}:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_ROOT_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_ROOT_PWD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_ADMIN_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_ADMIN_PWD}
      ME_CONFIG_MONGODB_SERVER: mongo

volumes:
  mongo_data:
