services:
  mongo:
    image: mongo:latest # ou "mongo:8.0" si tu veux figer la version
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: db
    volumes:
      - mongo_data:/data/db # persistance des données
      - ./init:/docker-entrypoint-initdb.d:ro # scripts .js/.sh optionnels au démarrage

  mongo-express:
    image: mongo-express:latest # petite interface d’admin web
    container_name: mongo-express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: db
      ME_CONFIG_BASICAUTH_USERNAME: admin # login UI
      ME_CONFIG_BASICAUTH_PASSWORD: admin

volumes:
  mongo_data: # named volume créé automatiquement
